repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1  # Replace with the latest version
    hooks:
      - id: flake8

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2  # Replace with the latest version
    hooks:
      - id: isort

