[tool.isort]
profile = "google"
force_single_line = false
combine_as_imports = true 
line_length = 100
lines_between_sections = 0
force_sort_within_sections = true
multi_line_output = 0
include_trailing_comma = false
force_grid_wrap = 0
use_parentheses = false   

